package com.after;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;

@Slf4j
public class jsonTest {

  @Test
  public void test1() {
    String jsonString =
        "{\n"
            + "  \"took\" : 4554,\n"
            + "  \"timed_out\" : false,\n"
            + "  \"_shards\" : {\n"
            + "    \"total\" : 48,\n"
            + "    \"successful\" : 48,\n"
            + "    \"skipped\" : 0,\n"
            + "    \"failed\" : 0\n"
            + "  },\n"
            + "  \"hits\" : {\n"
            + "    \"total\" : {\n"
            + "      \"value\" : 10000,\n"
            + "      \"relation\" : \"gte\"\n"
            + "    },\n"
            + "    \"max_score\" : null,\n"
            + "    \"hits\" : [ ]\n"
            + "  },\n"
            + "  \"aggregations\" : {\n"
            + "    \"groupByData\" : {\n"
            + "      \"buckets\" : [\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-01\",\n"
            + "          \"key\" : 1601481600000,\n"
            + "          \"doc_count\" : 257484,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 193011,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 128021\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 193011\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 64473,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 37092\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 64473\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-02\",\n"
            + "          \"key\" : 1601568000000,\n"
            + "          \"doc_count\" : 529394,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 400834,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 199263\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 400834\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 128560,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 53844\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 128560\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-03\",\n"
            + "          \"key\" : 1601654400000,\n"
            + "          \"doc_count\" : 538585,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 406181,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 202743\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 406181\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 132404,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 54931\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 132404\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-04\",\n"
            + "          \"key\" : 1601740800000,\n"
            + "          \"doc_count\" : 536077,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 387792,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 195769\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 387792\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 148285,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 58046\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 148285\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-05\",\n"
            + "          \"key\" : 1601827200000,\n"
            + "          \"doc_count\" : 506492,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 368611,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 192024\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 368611\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 137881,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 56772\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 137881\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-06\",\n"
            + "          \"key\" : 1601913600000,\n"
            + "          \"doc_count\" : 511006,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 366185,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 189566\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 366185\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 144821,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 57803\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 144821\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-07\",\n"
            + "          \"key\" : 1602000000000,\n"
            + "          \"doc_count\" : 486302,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 355627,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 186772\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 355627\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 130675,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 55071\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 130675\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-08\",\n"
            + "          \"key\" : 1602086400000,\n"
            + "          \"doc_count\" : 464261,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 344083,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 183388\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 344083\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 120178,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 54324\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 120178\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-09\",\n"
            + "          \"key\" : 1602172800000,\n"
            + "          \"doc_count\" : 405138,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 302374,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 173116\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 302374\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 102764,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49473\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 102764\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-10\",\n"
            + "          \"key\" : 1602259200000,\n"
            + "          \"doc_count\" : 426514,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 315208,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 174232\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 315208\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 111306,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49632\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 111306\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-11\",\n"
            + "          \"key\" : 1602345600000,\n"
            + "          \"doc_count\" : 482447,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 355660,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 186802\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 355660\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 126787,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 53185\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 126787\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-12\",\n"
            + "          \"key\" : 1602432000000,\n"
            + "          \"doc_count\" : 401611,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 298530,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 171767\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 298530\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 103081,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 48998\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 103081\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-13\",\n"
            + "          \"key\" : 1602518400000,\n"
            + "          \"doc_count\" : 408367,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 302968,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 170506\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 302968\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 105399,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49266\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 105399\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-14\",\n"
            + "          \"key\" : 1602604800000,\n"
            + "          \"doc_count\" : 492203,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 380298,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 220068\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 380298\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 111905,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49967\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 111905\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-15\",\n"
            + "          \"key\" : 1602691200000,\n"
            + "          \"doc_count\" : 461964,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 333016,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 178900\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 333016\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 128948,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 56791\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 128948\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-16\",\n"
            + "          \"key\" : 1602777600000,\n"
            + "          \"doc_count\" : 443148,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 324962,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 177959\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 324962\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 118186,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 54672\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 118186\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-17\",\n"
            + "          \"key\" : 1602864000000,\n"
            + "          \"doc_count\" : 514616,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 383815,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 185663\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 383815\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 130801,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 56918\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 130801\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-18\",\n"
            + "          \"key\" : 1602950400000,\n"
            + "          \"doc_count\" : 510417,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 375585,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 184703\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 375585\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 134832,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 55880\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 134832\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-19\",\n"
            + "          \"key\" : 1603036800000,\n"
            + "          \"doc_count\" : 407401,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 304459,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 171962\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 304459\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 102942,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 50213\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 102942\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-20\",\n"
            + "          \"key\" : 1603123200000,\n"
            + "          \"doc_count\" : 410019,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 306956,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 170418\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 306956\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 103063,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 50191\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 103063\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-21\",\n"
            + "          \"key\" : 1603209600000,\n"
            + "          \"doc_count\" : 428646,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 323743,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 187532\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 323743\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 104903,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 51019\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 104903\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-22\",\n"
            + "          \"key\" : 1603296000000,\n"
            + "          \"doc_count\" : 394776,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 298018,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 168408\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 298018\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 96758,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 48893\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 96758\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-23\",\n"
            + "          \"key\" : 1603382400000,\n"
            + "          \"doc_count\" : 397719,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 300955,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 168348\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 300955\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 96764,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 47948\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 96764\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-24\",\n"
            + "          \"key\" : 1603468800000,\n"
            + "          \"doc_count\" : 464235,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 343910,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 183291\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 343910\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 120325,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 54106\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 120325\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-25\",\n"
            + "          \"key\" : 1603555200000,\n"
            + "          \"doc_count\" : 462738,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 342051,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 179807\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 342051\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 120687,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 53972\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 120687\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-26\",\n"
            + "          \"key\" : 1603641600000,\n"
            + "          \"doc_count\" : 403130,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 301428,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 168315\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 301428\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 101702,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 50252\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 101702\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-27\",\n"
            + "          \"key\" : 1603728000000,\n"
            + "          \"doc_count\" : 393680,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 292929,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 166861\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 292929\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 100751,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49054\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 100751\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-28\",\n"
            + "          \"key\" : 1603814400000,\n"
            + "          \"doc_count\" : 399829,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 295198,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 166247\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 295198\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 104631,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49836\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 104631\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-29\",\n"
            + "          \"key\" : 1603900800000,\n"
            + "          \"doc_count\" : 405028,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 298426,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 168857\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 298426\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 106602,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 50161\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 106602\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-30\",\n"
            + "          \"key\" : 1603987200000,\n"
            + "          \"doc_count\" : 462739,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 351031,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 208873\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 351031\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 111708,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 50437\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 111708\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-10-31\",\n"
            + "          \"key\" : 1604073600000,\n"
            + "          \"doc_count\" : 497843,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 365038,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 187166\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 365038\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 132805,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 56512\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 132805\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-01\",\n"
            + "          \"key\" : 1604160000000,\n"
            + "          \"doc_count\" : 430892,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 306372,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 173534\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 306372\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 124520,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 55192\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 124520\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-02\",\n"
            + "          \"key\" : 1604246400000,\n"
            + "          \"doc_count\" : 401510,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 296631,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 169697\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 296631\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 104879,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 50126\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 104879\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-03\",\n"
            + "          \"key\" : 1604332800000,\n"
            + "          \"doc_count\" : 398181,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 293367,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 166062\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 293367\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 104814,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 50464\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 104814\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-04\",\n"
            + "          \"key\" : 1604419200000,\n"
            + "          \"doc_count\" : 488461,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 385143,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 236497\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 385143\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 103318,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49807\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 103318\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-05\",\n"
            + "          \"key\" : 1604505600000,\n"
            + "          \"doc_count\" : 403677,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 300064,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 168677\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 300064\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 103613,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49876\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 103613\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-06\",\n"
            + "          \"key\" : 1604592000000,\n"
            + "          \"doc_count\" : 410621,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 300782,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 165161\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 300782\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 109839,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 51149\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 109839\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-07\",\n"
            + "          \"key\" : 1604678400000,\n"
            + "          \"doc_count\" : 456970,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 333662,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 179385\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 333662\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 123308,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 55414\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 123308\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-08\",\n"
            + "          \"key\" : 1604764800000,\n"
            + "          \"doc_count\" : 461011,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 337328,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 177490\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 337328\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 123683,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 54554\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 123683\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-09\",\n"
            + "          \"key\" : 1604851200000,\n"
            + "          \"doc_count\" : 390010,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 289313,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 168500\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 289313\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 100697,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49391\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 100697\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-10\",\n"
            + "          \"key\" : 1604937600000,\n"
            + "          \"doc_count\" : 393532,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 290865,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 164834\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 290865\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 102667,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 50303\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 102667\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-11\",\n"
            + "          \"key\" : 1605024000000,\n"
            + "          \"doc_count\" : 389791,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 287750,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 162788\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 287750\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 102041,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49763\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 102041\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-12\",\n"
            + "          \"key\" : 1605110400000,\n"
            + "          \"doc_count\" : 395738,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 292377,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 167601\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 292377\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 103361,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49642\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 103361\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-13\",\n"
            + "          \"key\" : 1605196800000,\n"
            + "          \"doc_count\" : 448758,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 346958,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 209917\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 346958\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 101800,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 50094\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 101800\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-14\",\n"
            + "          \"key\" : 1605283200000,\n"
            + "          \"doc_count\" : 457417,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 335978,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 180667\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 335978\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 121439,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 53894\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 121439\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-15\",\n"
            + "          \"key\" : 1605369600000,\n"
            + "          \"doc_count\" : 458453,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 336574,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 179902\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 336574\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 121879,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 53975\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 121879\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-16\",\n"
            + "          \"key\" : 1605456000000,\n"
            + "          \"doc_count\" : 405341,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 304548,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 175270\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 304548\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 100793,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 50196\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 100793\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-17\",\n"
            + "          \"key\" : 1605542400000,\n"
            + "          \"doc_count\" : 429899,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 322197,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 173566\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 322197\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 107702,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 51335\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 107702\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-18\",\n"
            + "          \"key\" : 1605628800000,\n"
            + "          \"doc_count\" : 476133,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 368643,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 212472\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 368643\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 107490,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 51119\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 107490\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-19\",\n"
            + "          \"key\" : 1605715200000,\n"
            + "          \"doc_count\" : 422499,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 306281,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 171966\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 306281\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 116218,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 53839\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 116218\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-20\",\n"
            + "          \"key\" : 1605801600000,\n"
            + "          \"doc_count\" : 494944,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 384596,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 175261\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 384596\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 110348,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 53038\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 110348\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-21\",\n"
            + "          \"key\" : 1605888000000,\n"
            + "          \"doc_count\" : 748385,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 613927,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 192137\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 613927\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 134458,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 57845\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 134458\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-22\",\n"
            + "          \"key\" : 1605974400000,\n"
            + "          \"doc_count\" : 742650,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 610310,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 193746\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 610310\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 132340,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 57548\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 132340\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-23\",\n"
            + "          \"key\" : 1606060800000,\n"
            + "          \"doc_count\" : 605583,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 496849,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 180540\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 496849\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 108734,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 52197\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 108734\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-24\",\n"
            + "          \"key\" : 1606147200000,\n"
            + "          \"doc_count\" : 605536,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 493785,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 171306\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 493785\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 111751,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 51504\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 111751\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-25\",\n"
            + "          \"key\" : 1606233600000,\n"
            + "          \"doc_count\" : 792903,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 677666,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 223946\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 677666\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 115237,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 52202\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 115237\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-26\",\n"
            + "          \"key\" : 1606320000000,\n"
            + "          \"doc_count\" : 735047,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 628787,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 169481\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 628787\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 106260,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 51469\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 106260\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-27\",\n"
            + "          \"key\" : 1606406400000,\n"
            + "          \"doc_count\" : 935340,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 780010,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 213720\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 780010\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 155330,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 51902\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 155330\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-28\",\n"
            + "          \"key\" : 1606492800000,\n"
            + "          \"doc_count\" : 850034,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 717092,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 185617\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 717092\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 132942,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 56267\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 132942\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-29\",\n"
            + "          \"key\" : 1606579200000,\n"
            + "          \"doc_count\" : 773971,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 652081,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 177526\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 652081\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 121890,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 55448\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 121890\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-11-30\",\n"
            + "          \"key\" : 1606665600000,\n"
            + "          \"doc_count\" : 661197,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 564625,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 166151\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 564625\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 96555,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 49183\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 96555\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 3,\n"
            + "                \"doc_count\" : 17,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 8\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 17\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-12-01\",\n"
            + "          \"key\" : 1606752000000,\n"
            + "          \"doc_count\" : 537859,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 426493,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 161180\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 426493\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 105488,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 51787\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 105488\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 3,\n"
            + "                \"doc_count\" : 5878,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 3257\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 5878\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-12-02\",\n"
            + "          \"key\" : 1606838400000,\n"
            + "          \"doc_count\" : 569200,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 448939,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 257481\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 448939\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 109615,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 53287\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 109615\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 3,\n"
            + "                \"doc_count\" : 10646,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 4679\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 10646\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-12-03\",\n"
            + "          \"key\" : 1606924800000,\n"
            + "          \"doc_count\" : 419456,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 292039,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 166402\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 292039\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 117146,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 53846\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 117146\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 3,\n"
            + "                \"doc_count\" : 10271,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 4330\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 10271\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-12-04\",\n"
            + "          \"key\" : 1607011200000,\n"
            + "          \"doc_count\" : 287449,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 204226,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 142006\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 204226\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 76538,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 45424\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 76538\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 3,\n"
            + "                \"doc_count\" : 6685,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 3683\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 6685\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  }\n"
            + "}\n";
    JSONObject jsonObject = (JSONObject) (JSONObject.parseObject(jsonString)).get("aggregations");
    JSONObject jsonObject1 = jsonObject.getJSONObject("groupByData");
    JSONArray jsonArray = jsonObject1.getJSONArray("buckets");
    for (int i = 0; i < jsonArray.size(); i++) {
      JSONObject jsonObject2 = jsonArray.parseObject(jsonArray.get(i).toString());
      log.info("時間：{}", jsonObject2.get("key_as_string"));
      JSONArray jsonArrayData =
          JSONArray.parseArray(
              ((JSONObject) jsonObject2.get("termServiceProvider")).get("buckets").toString());
      for (int j = 0; j < jsonArrayData.size(); j++) {
        JSONObject jsonObject3 = JSONObject.parseObject(jsonArrayData.get(j).toString());
        String name = "电信";
        if (jsonObject3.get("key").toString().equals("2")) {
          // 运营商telecom 1，2 mobile，3 unicom
          name = "移动";
        } else if (jsonObject3.get("key").toString().equals("3")) {
          name = "联通";
        }
        System.out.println(
name
        + "  ---认证总数  "
        + JSONObject.parseObject(jsonObject3.get("authTimes").toString()).get("value")
        + "  ---用户总数  "
                + JSONObject.parseObject(jsonObject3.get("authAccountNum").toString()).get("value")
                );
      }
    }
  }
}
