package com.after;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;

@Slf4j
public class jsonTest {

  @Test
  public void test1() {
    String jsonString =
        "{\n"
            + "  \"took\" : 2165,\n"
            + "  \"timed_out\" : false,\n"
            + "  \"_shards\" : {\n"
            + "    \"total\" : 48,\n"
            + "    \"successful\" : 48,\n"
            + "    \"skipped\" : 0,\n"
            + "    \"failed\" : 0\n"
            + "  },\n"
            + "  \"hits\" : {\n"
            + "    \"total\" : {\n"
            + "      \"value\" : 10000,\n"
            + "      \"relation\" : \"gte\"\n"
            + "    },\n"
            + "    \"max_score\" : null,\n"
            + "    \"hits\" : [ ]\n"
            + "  },\n"
            + "  \"aggregations\" : {\n"
            + "    \"groupByData\" : {\n"
            + "      \"buckets\" : [\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-12-04\",\n"
            + "          \"key\" : 1607011200000,\n"
            + "          \"doc_count\" : 192412,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 134267,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 93442\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 134267\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 53579,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 32385\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 53579\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 3,\n"
            + "                \"doc_count\" : 4566,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 2472\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 4566\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-12-05\",\n"
            + "          \"key\" : 1607097600000,\n"
            + "          \"doc_count\" : 444883,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 315448,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 173792\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 315448\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 118678,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 54769\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 118678\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 3,\n"
            + "                \"doc_count\" : 10757,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 4579\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 10757\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-12-06\",\n"
            + "          \"key\" : 1607184000000,\n"
            + "          \"doc_count\" : 478574,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 339493,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 181461\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 339493\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 127997,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 55457\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 127997\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 3,\n"
            + "                \"doc_count\" : 11084,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 4520\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 11084\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        },\n"
            + "        {\n"
            + "          \"key_as_string\" : \"2020-12-07\",\n"
            + "          \"key\" : 1607270400000,\n"
            + "          \"doc_count\" : 325226,\n"
            + "          \"termServiceProvider\" : {\n"
            + "            \"doc_count_error_upper_bound\" : 0,\n"
            + "            \"sum_other_doc_count\" : 0,\n"
            + "            \"buckets\" : [\n"
            + "              {\n"
            + "                \"key\" : 2,\n"
            + "                \"doc_count\" : 233353,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 151482\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 233353\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 1,\n"
            + "                \"doc_count\" : 84525,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 47732\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 84525\n"
            + "                }\n"
            + "              },\n"
            + "              {\n"
            + "                \"key\" : 3,\n"
            + "                \"doc_count\" : 7348,\n"
            + "                \"authAccountNum\" : {\n"
            + "                  \"value\" : 3890\n"
            + "                },\n"
            + "                \"authTimes\" : {\n"
            + "                  \"value\" : 7348\n"
            + "                }\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  }\n"
            + "}\n";
    JSONObject jsonObject = (JSONObject) (JSONObject.parseObject(jsonString)).get("aggregations");
    JSONObject jsonObject1 = jsonObject.getJSONObject("groupByData");
    JSONArray jsonArray = jsonObject1.getJSONArray("buckets");
    for (int i = 0; i < jsonArray.size(); i++) {
      JSONObject jsonObject2 = jsonArray.parseObject(jsonArray.get(i).toString());
      log.info("時間：{}", jsonObject2.get("key_as_string"));
      JSONArray jsonArrayData =
          JSONArray.parseArray(
              ((JSONObject) jsonObject2.get("termServiceProvider")).get("buckets").toString());
      for (int j = 0; j < jsonArrayData.size(); j++) {
        JSONObject jsonObject3 = JSONObject.parseObject(jsonArrayData.get(j).toString());
        String name = "电信";
        if (jsonObject3.get("key").toString().equals("2")) {
          // 运营商telecom 1，2 mobile，3 unicom
          name = "移动";
        } else if (jsonObject3.get("key").toString().equals("3")) {
          name = "联通";
        }
        System.out.println(
name
        + "  ---认证总数  "
        + JSONObject.parseObject(jsonObject3.get("authTimes").toString()).get("value")
        + "  ---用户总数  "
                + JSONObject.parseObject(jsonObject3.get("authAccountNum").toString()).get("value")
                );
      }
    }
  }
}
