spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08

server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8


